security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MPM\BancoBundle\Entity\Persona: sha512

    providers:
        main:
            entity:
                class: MPM\BancoBundle\Entity\Persona
                property: dni
    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: banco_homepage
            anonymous: ~
            remember_me:
                  key:      "%secret%"
                  lifetime: 31536000 # 365 days in seconds
                  path:     /
                  domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: 'ROLE_USER' }
        - { path: ^/personas, roles: 'ROLE_ADMIN' }
