security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MPM\BancoBundle\Entity\Persona: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: MPM\BancoBundle\Entity\Persona
                property: dni
    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: banco_homepage
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: 'ROLE_USER' }
        - { path: ^/personas, roles: 'ROLE_ADMIN' }
