<?php

namespace MPM\BancoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtraccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraccionRepository extends EntityRepository
{
}
