<?php

namespace MPM\BancoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciaRepository extends EntityRepository
{
}
